### ISSUE TITLE
Syntax and Title is Incorrect

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs-ddi#120] opened 2018-06-11 22:13 UTC
It is union, not struct.

Line 37035 of wdm.h in wdk 10.0.17134.0

typedef union _OB_POST_OPERATION_PARAMETERS {
    \_In\_ OB_POST_CREATE_HANDLE_INFORMATION       CreateHandleInformation;
    \_In\_ OB_POST_DUPLICATE_HANDLE_INFORMATION    DuplicateHandleInformation;
} OB_POST_OPERATION_PARAMETERS, *POB_POST_OPERATION_PARAMETERS;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b6009a8-01bf-3d55-2fcc-7ea50e11f938
* Version Independent ID: af510ab5-fa46-8b82-6353-4822c1a9c79e
* Content: [_OB_POST_OPERATION_PARAMETERS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_ob_post_operation_parameters)
* Content Source: [wdk-ddi-src/content/wdm/ns-wdm-_ob_post_operation_parameters.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/ns-wdm-_ob_post_operation_parameters.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment] 2018-06-11 22:16
Thanks, @hsebs 
Functionally, this is a duplicate of Issue #116. Will be fixed when we fix that bug.

**Closed by EliotSeattle** 2018-06-11 22:16 UTC
Labels: duplicate
