### ISSUE TITLE
Insufficient documentation in PFND3D12DDI_MAPHEAP 

### ISSUE THREAD

**Issue by carlossanlop** [MicrosoftDocs/windows-driver-docs-ddi#923] opened 2020-08-06 19:51 UTC
The documentation for this API insufficient and should have better descriptions:

https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3d12umddi/nc-d3d12umddi-pfnd3d12ddi_mapheap.md

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d12umddi/nc-d3d12umddi-pfnd3d12ddi_mapheap

This request comes from negative feedback on Twitter related to this.

cc @tedhudek @mimisasouvanh @IrinVoso @lorihollasch who have modified this file in the past.

**Comment by EliotSeattle** [comment] 2020-08-06 19:58
I believe that this is a duplicate of Issue #922

**Closed by EliotSeattle** 2020-08-06 19:58 UTC
Labels: Pri3, doc-enhancement, duplicate
