### ISSUE TITLE
duplicated PhysicalAddress field in the doc

### ISSUE THREAD

**Issue by chaotsungpeng** [MicrosoftDocs/windows-driver-docs-ddi#1284] opened 2022-04-07 13:40 UTC
typedef struct _DXGK_ALLOCATIONLIST
{
    HANDLE              hDeviceSpecificAllocation;
    struct
    {
        UINT            WriteOperation  : 1;    // 0x00000001
        UINT            SegmentId       : 5;    // 0x0000002E
        UINT            Reserved        : 26;   // 0xFFFFFFC0
    };
#if (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_0)
    union
    {
        PHYSICAL_ADDRESS    PhysicalAddress;
        D3DGPU_VIRTUAL_ADDRESS VirtualAddress;
    };
#else // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_0)
    PHYSICAL_ADDRESS    PhysicalAddress;
#endif // (DXGKDDI_INTERFACE_VERSION >= DXGKDDI_INTERFACE_VERSION_WDDM2_0)
} DXGK_ALLOCATIONLIST;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69682ac4-a065-8b83-8f16-086463be977d
* Version Independent ID: 9e0069d3-73b5-939f-3935-245f8c68e87b
* Content: [_DXGK_ALLOCATIONLIST (d3dkmddi.h) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ns-d3dkmddi-_dxgk_allocationlist)
* Content Source: [wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_allocationlist.md](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/d3dkmddi/ns-d3dkmddi-_dxgk_allocationlist.md)
* Product: **windows-hardware**
* Technology: **wdk-api-reference**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment] 2022-04-22 02:05
@chaotsungpeng, I'm closing this issue as it is a duplicate of #1283.

**Closed by lorihollasch** 2022-04-22 02:05 UTC
Labels: Pri2, windows-hardware/prod, wdk-api-reference/tech
